# SPDX-License-Identifier: MIT
---
- name: Example aide role invocation
  hosts: all
  tasks:
    - name: Include role aide
      tags:
        - install
        - generate_config
        - init
        - check
        - update
      vars:
        aide_db_fetch_dir: /tmp
      ansible.builtin.include_role:
        name: aide
