---
- name: change user password hurlburt accounts
  hosts: all
  vars_files:
    - /etc/ansible/vars/vault/users.yml

  tasks:
    - name: change password for dmz root
      ansible.builtin.user:
        name: root
        state: present
        password_lock: false
        password: "{{ root_pass | password_hash('sha512') }}"
#      when: inventory_hostname in groups["hrt_dmz"]

    - name: change password for dmz defadmin
      ansible.builtin.user:
        name: defadmin
        state: present
        password_lock: false
        password: "{{ defadmin_pass | password_hash('sha512') }}"
#      when: inventory_hostname in groups["hrt_dmz"]

    - name: change password for cstrawn.adm
      ansible.builtin.user:
        name: cstrawn.adm
        state: present
        password_lock: false
        password: "{{ cstrawn_pass | password_hash('sha512') }}"
