---
- name: Copy, execute, and delete check_home_directory_ownership.sh script
  hosts: all
  vars:
    script_path: "/srv/check_home_directory_ownership.sh"
  tasks:
    - name: Copy the check_home_directory_ownership.sh script to remote host
      copy:
        src: templates/check_home_directory_ownership.sh
        dest: "{{ script_path }}"
        mode: '0700'

    - name: Execute the check_home_directory_ownership.sh script
      command: "{{ script_path }}"
      register: results
      
    - debug:
        var: results.stdout

    - name: Delete the check_home_directory_ownership.sh script
      file:
        path: "{{ script_path }}"
        state: absent
