- name: Manage crypto policies
  hosts: all
  roles:
    - role: linux-system-roles.crypto_policies
      vars:
        crypto_policies_policy: "FIPS:AD-SUPPORT"
        crypto_policies_reload: true
        crypto_policies_reboot_ok: true