---
- name: Install multiple packages
  hosts: dnf
  tasks: 
    - name: Install packages
      dnf:
        name: 
          - rhc-worker-playbook
          - unzip
          - wget
        state: latest
