- hosts: dnf
  become: true
  become_user: root
  tasks:
  - name: Upload insight-client results
    shell:
      
  - name: Update all installed packages using DNF module
    dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: dnf_update_status

  - name: Remove packates not needed anymore
    dnf:
      autoremove: yes

  - name: Reboot when packages were updated
    reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
    when: dnf_update_status.change
