---
- name: List Available DNF Updates
  hosts: dnf
  tasks:
    - name: List Available Updates using dnf check-update
      command: dnf check-update --quiet
      register: dnf_updates
      changed_when: false

    - name: Parse available updates
      set_fact:
        packages: "{{ dnf_updates.stdout_lines | select('search', '^[a-zA-Z0-9]') | map('split', ' ') | map('first') | list }}"

    - name: Print the package facts
      debug:
        msg: |
          {% for package in packages %}
          {{ package }}
          {% endfor %}
