---
- hosts: dnf
  tasks:
  - name: List Available Patches (Non-Kernel)
    dnf:
      list: updates
      update_cache: true
    register:   my_packages: "{{ dict(packages.results|groupby('name')) }}"

  - name: Print the package facts
    debug:
      msg: |
        {% for name,versions in my_packages.items() %}
        {% set max_ver=versions|map(attribute='version')|max %}
        {% set p=versions|selectattr('version', '==', max_ver) %}
        {{ name }}-{{ p.0.version }}-{{ p.0.release }} 
        {% endfor %}