- hosts: all

  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_stig
    oscap_policy: ssg-rhel8-ds
    oscap_version: 0.1.76
    dir_path: /usr/local/bin/scap-security-guide

  tasks:

  - name: install openscap scanner
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - openscap-scanner
    - scap-security-guide

  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    ansible.builtin.unarchive:
      src: https://github.com/ComplianceAsCode/content/releases/download/v{{ oscap_version }}/scap-security-guide-{{ oscap_version }}.zip
      dest: /usr/local/bin/
      remote_src: yes

  - block:
    - name: run openscap
      command: oscap --quiet xccdf eval \
        --profile {{ oscap_profile }} \
        --results-arf /usr/local/bin/scap-security-guide-{{ oscap_version }}/oscap-arf.xml \
        --report /usr/local/bin/scap-security-guide-{{ oscap_version }}/oscap-report.html \
        --fetch-remote-resources \
        /usr/local/bin/scap-security-guide-{{ oscap_version }}/{{ oscap_policy }}.xml > /dev/null 2>&1

    always:
    - name: download report
      fetch:
        src: /usr/local/bin/scap-security-guide-{{ oscap_version }}/oscap-report.html
        dest: /tmp/reports/{{ inventory_hostname }}.html
        flat: yes
#    - name: Copy file with owner and permissions
#      ansible.builtin.copy:
#        src: /tmp/oscap-report.html
#        dest: /etc/foo.conf
#        owner: foo
#        group: foo
#        mode: '0644'

    - name: Recursively remove directory
      ansible.builtin.file:
        path: /usr/local/bin/scap-security-guide-{{ oscap_version }}
        state: absent