---
- name: Registering system using activation key and organization ID
  hosts: deploy
  roles:
    - role: rhel-system-roles.rhc
  vars:
    rhc_auth:
      activation_keys:
        keys:
          -  "digdag_me_26"
    rhc_organization: 6157000
