---
- name: Registering system using activation key and organization ID
  hosts: deploy
  roles:
    - role: redhat.rhel_system_roles.rhc
  vars:
    rhc_auth:
      activation_keys:
        keys:
          -  "{{ activationKey }}"
    rhc_organization: 6157000
