---
- hosts: all
  gather_facts: true
  tasks:
  - name: Downloading UF
    get_url:
      url: https://download.splunk.com/products/universalforwarder/releases/9.3.1/linux/splunkforwarder-9.3.1-0b8d769cb912.x86_64.rpm
      dest: /srv/splunforwarder.rpm
      mode: '0755'
    register: download
  
  - name: Install Splunkservers
    dnf:
      name: /srv/splunforwarder.rpm
      state: present
      disable_gpg_check: true
  
  - name: Splunk Start
    command:
      cmd: /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt --seed-password RT@#fghtVJYd
#    become_user: splunkfwd
    ignore_errors: true
  
  - name: Boot Start
    command:
      cmd: /opt/splunkforwarder/bin/splunk enable boot-start -user splunkfwd
#    ignore_errors: true
    async: 10
    poll: 0
  
  - name: Make Deployment Client
    command:
#      cmd: /opt/splunkforwarder/bin/splunk set deploy-poll 172.16.30.106:8089 -auth admin:RT@#fghtVJYd
      cmd: /opt/splunkforwarder/bin/splunk set deploy-poll 172.16.30.106:8089
 #   ignore_errors: true
    become_user: splunkfwd
  
  - name: Splunk Restart
    command:
      cmd: /opt/splunkforwarder/bin/splunk restart

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /srv/splunforwarder.rpm
      state: absent
