---
- hosts: deploy
  vars:
    - PermitSAGroups: core_network_engineers@sofpi.sofapps.dev
  tasks:
    - name: Realm Remove All
      command: realm deny --all
      
    - name: Realm Permit Access to  {{ PermitSAGroups }}
      command: realm permit -g '{{ PermitSAGroups }}'

    - name: Check if {{ PermitSAGroups }} exist in /etc/sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '^%{{ PermitSAGroups }}'
        line: '%{{ PermitSAGroups }} ALL=(ALL)ALL'
        validate: 'visudo -cf %s'

    - name: Install mkhomedir
      dnf:
        name:
        - oddjob-mkhomedir
        - oddjob
        state: latest

    - name: Enable mkhomdir in authprofile
      command: authselect enable-feature with-mkhomedir

    - name: Make sure a service unit is running
      systemd_service:
        enabled: true
        state: started
        name: oddjobd
