---
- hosts: all
  tasks:
  - name: Clean cache dnf
    ansible.builtin.shell: dnf clean all
    ignore_errors: yes
  
  - name: Update all installed packages using dnf module
    dnf:
      name: '*'
      state: latest
      update_cache: true
      update_only: true
    register: dnf_update_status
    when: ansible_os_family == "RedHat"

  - name: Remove packates not needed anymore
    dnf:
      autoremove: true
    when: ansible_os_family == "RedHat"

#  - name: Reboot when packages were updated
#    reboot:
#      post_reboot_delay: 60
#    register: dnf_reboot_status
#    when: dnf_update_status.changed

  - name: Reboot in 120 seconds
    ansible.builtin.command: /usr/sbin/shutdown -r +2
    when: dnf_update_status.changed
    
