---
- hosts: all
  become: true

  tasks:
    - name: Clean DNF cache
      ansible.builtin.command: dnf clean all
      changed_when: false
      ignore_errors: true

    - name: Apply security updates first
      ansible.builtin.dnf:
        name: "*"
        state: latest
        security: true
        update_cache: true
        update_only: true
      register: security_update_status
      when: ansible_os_family == "RedHat"
	  
    - name: Clean DNF cache part 2
      ansible.builtin.command: dnf clean all
      changed_when: false
      ignore_errors: true

    - name: Apply remaining updates
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
      register: dnf_update_status
      when: ansible_os_family == "RedHat"

    - name: Remove packages no longer needed
      ansible.builtin.dnf:
        autoremove: true
      when: ansible_os_family == "RedHat"

    - name: Reboot in 120 seconds if updates were installed
      ansible.builtin.command: /usr/sbin/shutdown -r +2
      when:
        - ansible_os_family == "RedHat"
        - security_update_status.changed or dnf_update_status.changed
