---
- hosts: deploy
  tasks:
    - name: Another symbolic mode example, adding some permissions and removing others
      ansible.builtin.copy:
        src: logrotate.yml
        dest: /srv/foo.conf
        owner: ansible
        group: ansible
        mode: u+rw,g-wx,o-rwx
