---
- name: Deploy tmux template
  hosts: all
  tasks:
  - name: Template a file to /etc/profile.d/tmux.sh
    ansible.builtin.template:
      src: templates/tmux.j2
      dest: /etc/profile.d/tmux.sh
      owner: root
      group: root
      mode: '0644'
