---
- name: change user password accounts
  hosts: all
  tasks:
    - name: change password for defadmin
      ansible.builtin.user:
        name: defadmin
        state: present
        password_lock: false
        password: "{{ defadmin_pass | password_hash('sha512') }}"
        no_log: true

    - name: change password for cstrawn
      ansible.builtin.user:
        name: cstrawn.adm
        state: present
        password_lock: false
        password: "{{ cstrawn_pass | password_hash('sha512') }}"
        no_log: true

    - name: change password for root
      ansible.builtin.user:
        name: root
        state: present
        password_lock: false
        password: "{{ root_pass | password_hash('sha512') }}"
        no_log: true

    - name: change password for acas
      ansible.builtin.user:
        name: svc_acas
        state: present
        password_lock: false
        password: "{{ acas_pass | password_hash('sha512') }}"
        expires: 1798675200
        no_log: true

    - name: change password for ansible
      ansible.builtin.user:
        name: ansible
        state: present
        password_lock: false
        password: "{{ ansible_pass | password_hash('sha512') }}"
        expires: 1798675200
        no_log: true
