---
- name: change user password accounts
  hosts: all
  tasks:
    - name: change password for internal defadmin
      ansible.builtin.user:
        name: defadmin
        state: present
        password_lock: false
        password: "{{ defadmin_pass | password_hash('sha512') }}"

    - name: change password for cstrawn
      ansible.builtin.user:
        name: cstrawn.adm
        state: present
        password_lock: false
        password: "{{ cstrawn_pass | password_hash('sha512') }}"

    - name: change password for internal root
      ansible.builtin.user:
        name: root
        state: present
        password_lock: false
        password: "{{ root_pass | password_hash('sha512') }}"
